etmc/tmLQCD

solver/eigcg.c
solver/incr_eigcg.c

Hi:
I fixed a bug in the convergence test for eigcg. 
Thanks
Abdou

Fixed a bug in the convergence test for eigcg

---

update_tm.c

add trajectory counter to return_check.data and provide a number also for the relative reversibility violation, ddh/dh, in addition to ddh/H

update_tm reversibility check

---

solver/rg_mixed_cg_her.c
solver/rg_mixed_cg_her_nd.c

respect the maximum number of iterations defined in input file and adjust computation of maximum number of outer iterations somewhat

rg_mixed_cg_her: respect maximum number of iterations

---

monomial/cloverdetratio_rwmonomial.c
monomial/monomial.c
reweighting_factor.c
sample-input/sample-rw.input

Reweighting

---

global.h
io/utils_write_first_message.c
test/test_eigenvalues.c

remove g_ka_csw_8 to fix issue #274

---

invert.c
invert_eo.c
io/params.h
operator.c
read_input.l

Add SRC_TYPE enum to io/params.h to have understandable values for the source type.
In addition, minor refactoring of invert.c

clean up source types for SourceInfo.type

---

invert_doublet_eo.c

we missed one instance of MPI, which was written as
defined(MPI)
which is corrected now

found overlooked instances of defined MPI

---

.gitignore
DDalphaAMG_interface.c
DDalphaAMG_interface.h
configure.in
hmc_tm.c
read_input.h
read_input.l

In response to issue #346.
@kostrzewa @urbach What do you think about this solution?

Fixing compilation without DDalphaAMG

---

doc/Makefile
doc/main.tex

adjust parameters and use 'graphicx' package such that the docs can be built using pdflatex, add Makefile for automatic generation of documentation usign latexmk

documentation: make building easier and allow use of pdflatex

---

quda_interface.c

support twisted mass flavour choice in current quda develop branch

quda_interface: support current inv_param setup for mu and clover term

---

default_input_values.h
invert_clover_eo.c
linalg/convert_eo_to_lexic.c
linalg/convert_eo_to_lexic.h
operator.c
operator.h
operator/clovertm_operators.c
operator/clovertm_operators.h
operator_types.h
qphix_base_classes.hpp
qphix_interface.cpp
qphix_interface.h
qphix_test_Dslash.c

* full 4D parallelisation
* more meaningfull test structure for operators
* eo spinor packers
* reworked gauge packer
* clover field packers

QPhiX support for all degenerate operators in the inverter

---

config.h.in
configure.in
include/tmLQCD.h
invert.c
invert_clover_eo.c
invert_doublet_eo.c
invert_eo.c
io/utils_write_first_message.c
meas/correlators.c
meas/measurements.c
meas/measurements.h
operator.c
quda_interface.c
quda_types.h
read_input.h
read_input.l

Also fixes a few small bugs and cleans up some parts of the QUDA integration. Contains #388

Add support for forced (A)PBC in QUDA interface

---

quda_interface.c

(this version of the code has never been used in production). Do not reorder the input spinor after the inversion (not sure why this was ever done). In addition, use threads in reordering routines.

Invert the correct flavour in invert_quda_direct 

---

qphix_interface.cpp

call all QPhiX solvers which support it with the QPhiX::RELATIVE flag, thus making explicit how we make the tmLQCD and QPhiX residuals agree for whatever is given in the input file

qphix_interface adjust for new residual flag in QPhiX

---

offline_measurement.c
read_input.l

Dash in filename

---

configure.in
default_input_values.h
quda_interface.c
quda_types.h
read_input.l

refreshes the setup correctly but then leads to the solve failing with a QUDA error coming from GCR
Will open an issue with the QUDA devs to see what we're doing incorrectly.

first implementation of MG setup refresh 

---

io/gauge_read.c
misc_types.h
start.c

This is a compantion PR to #522

call tm_update_gauge_id also from random_gauge_field and unit_g_gauge_field

---

.gitignore
NEWS
doc/input.tex
doc/overview.tex
hmc_tm.c
read_input.l
test/test_eigenvalues.c

Please see https://github.com/etmc/tmLQCD/commit/d197c0cc349710e636cc15737ed80f226d1e4221.
I tested this in a simple case and works as expected.

nstore_counter not hidden

---

meas/gradient_flow.c
meas/measurements.h
quda_interface.c
quda_interface.h
read_input.l

Wflow is working but the output goes to stdout

Quda work add actions wflow

---

doc/input.tex

Following what is done in `read_input.l`, I've added the documentation for the gradient flow online measurement.

Documentation gradient gflow

---

quda_interface.c

output the values of mubar, epsbar, kappa and csw passed to invert_doublet_eu_quda

---

quda_interface.c

I've been wanting to fix this for ages now.

suppress message about MgSetup2KappaMu if it does not differ from current mu

---

.github/workflows/basic-build.yaml
.github/workflows/ddalphaamg-build.yaml
.github/workflows/qphix-build.yaml
quda_interface.c

Do we also need some compile time variable to compile with an old version of QUDA? 
Something like `#ifdef TM_QUDA_mrhs`.

add  mg_param->n_vec_batch[level]

---

reweighting_factor.c

Branch for testing  `reweighting_factor.c`

fix printing typo

---

quda_interface.c

In principle this should fix #622, test run is queued on Juwels Booster

only use MGSetup2KappaMu if it has actually been set
