etmc/tmLQCD

offline_measurement.c
Due to an oversight offline_measurement could not be compiled. This fixes the problem.
=> offline_measurement: fix failed compilation of offline_measuremet

read_input.l
The Cray compiler complains about not being able to find the rmQuotes function. Declaring it ```static inline void``` seems to fix the problem.
=> read_input: make rmQuotes static inline void to satisfy Cray compiler

matrix_utils.c
hmm, somehow I never tested this with SSE ...
We could also include `global.h` instead, but this would create more dependencies.
=> sse.h was not included when configured for SSEX usage

monomial/cloverdet_monomial.c, monomial/det_monomial.c
*det_acc: increment rather than assign iteration count for acceptance step to get consistent counts across all monomials when reversitibility check is run
=> consistent iteration counts for determinant monomial when reversibility check is done

benchmark.c
both for E/O H and D_psi, estimate the number of iterations required for ~31 seconds of benchmarking time and provide more structured output, appropriate for preparing scaling information for computer time applications
further down the line this needs to be cleaned up and provide benchmarking interfaces for complete operators, including little_D if possible
=> benchmark: estimate appropriate number of iterations and give structured output

update_tm.c
When a reversibility check is performed, write the correct trajectory metadata into the configuration. Up to now this was set to -1 for some reason.
=> correct trajectory metadata when reversibility check is performed

default_input_values.h
after adding RGMIXEDCG, the default solver type for the ND monomial was incorrect
=> fix default solver type for ND monomial

invert.c
for safety reasons it is probably better to initialise ranlux with the seed XOR'ed
=> invert: initialise the ranlux seed XOR'ed with nstore

gen_sources.c, invert.c, meas/correlators.c, meas/measurements.c, meas/measurements.h, prepare_source.c, prepare_source.h, source_generation.c, source_generation.h
this is making the random numbers used in the function `source_generation_pion_only` depending on `random_seed`. Note that once this is merged, we loose reproducability to previous computations using pion times slice sources.
=> Source Seed

global.h, io/spinor_read.c, read_input.l
Allow the user to disable the IO check for the reading of sources, 
independently from the gauge IO checks. 
'DisableGaugeIOChecks' parameter added for consistency and
'DisableIOChecks' retained for backwards compatibility. The latter
disables only gauge IO checks, as it used to be.
=> read_spinor: add new flag 'DisableSourceIOChecks' 

DDalphaAMG_interface.c, hmc_tm.c, io/gauge_read.c, update_tm.c
In response to the issues reported by @kostrzewa:
> - when using the DDlpahaAMG interface in invert, the MG setup is updated when the source changes or the flavour is switched, unless I set MGUpdateSetupIter = 0.
> 
> - Worse still, when processing multiple gauge configurations in one job, I've noticed that the DDalphaAMG interface will not update its copy of  the gauge configuration between gauge configurations. This is true whatever value I set MGUpdateSetupIter to. After the new gauge configuration has been read in, it will
> a) do MGUpdateSetupIter setup iterations (without updating the gauge field first), if MGUpdateSetupIter > 0
> b) attempt to do one inversion, notice that the result is wrong, and restart.
>
> Only after this restart will the gauge field be updated and the setup1 …
=> Some bug fix about MG_update.

config.h.in
The previous header of `config.in.h` suggested that it has been
auto-generated with `autoheader`. tmLQCD does not use the full set of
GNU Autotools, so that file is hand-written.
In order to prevent future confusion, the first line now explicitly
states that it is hand-written.
=> Update the header of config.in.h (closes GH-364)

.travis.yml, travis-ci.sh
To actually build on Travis CI, go to https://travis-ci.org/etmc/tmLQCD
and log in with an account having admin rights on that repository. There
should be a switch to enable building. Then it is automatically
integrated with GitHub.
Currently it uses one of the HMC input files to run it. It would be even
better to use some proper unit test. The current usage is a “smoke test”
(as in “Does it smoke when it is turned on?”) only.
=> Add Travis CI support

operator/D_psi.c
This is a fix to issue #393.
The problem are the explicit SSE version of non-even/odd D_psi and
Dsw_psi.
The only feasible workaround at the moment is to disable SSE2|3 in
D_psi.
This will not affect the even/odd versions, which are still available
in SSE2|3.
In the future we'll remove these macros completely.
=> Fix issue #393

default_input_values.h, doc/Makefile, kahan_summation.h, meas/Makefile.in, meas/field_strength_types.h, meas/gradient_flow.c, meas/measure_clover_field_strength_observables.c, meas/measure_clover_field_strength_observables.h, meas/measurements.h, omp_accumulator.h, read_input.l, tensors.h
=> gradflow topological charge measurement

Makefile.in, doc/rational.tex, hmc_tm.c, init/Makefile.in, init/init_gauge_fg.c, init/init_gauge_fg.h, integrator.c, integrator.h, monomial/ndratcor_monomial.c, read_input.l, update_momenta_fg.c, update_momenta_fg.h, update_tm.c
Saved some applications of Z in both heatbath/acc step.
Improved the check of next order correction in both heatbath/acc step (which we should discuss if it was a bug; read following).
Added documentation for guiding the changes.
Everything tested and gives same results of before.
A test is running on supermuc for the ensemble 16c Nf=1+1 with changes included, using just DDalphaAMG. You can find it in /gpfs/work/pr74yo/di49saj/HMC_MG_nd_only_test.
@urbach @kostrzewa @Finkenrath 
-------------------
The improvements in the checks for next order correction are the following; 
we should discuss if it was a bug.
The old check for the order `n`th was
`| Z^n R |^2 < acceptance^2`
which reads as `R^\dagger Z^{2n} R `.
The new check is
`[ c_n R^\dagger Z^n R ]^2 < acceptance^2`
which is actually …
=> Improvements to correction monomial

include/tmLQCD.h, wrapper/lib_wrapper.c
expose global.h and struct_accessors.h through tmLQCD.h, return error state in lib_wrapper if invert.input cannot be found
=> tmLQCD_invert_init should return if the input file cannot be found

wrapper/lib_wrapper.c
When used as a library, the gauge field can be loaded via the external application by passing an integer configuration number to ```tmLQCD_read_gauge```. Unfortunately, doing so does not set ```nstore```and thus tmLQCD may be left in an inconsistent state.
=> using tmLQCD via libwrapper leads to inconsistent nstore

quda_interface.c
This prevents issues with newest QUDA versions and makes the code faster to boot!
=> quda_interface: set two forgotten precision parameters 

update_tm.c
The xlf-info LIME record contained a wrong value of the plaquette when the reversibility check occurs.
To reproduce it, take for instance "sample-input/sample-hmc0.input" and set (to make it simpler and faster) for instance:
Measurements = 11
ReversibilityCheckIntervall = 10
The plaquette value in the "xlf-info" header of the resulting conf is wrong (it corresponds to the plaquette computed on the reversed trajectory).
I checked that the averaged plaquette computed and the value written in "output.data" agree and both disagree with the value in the "xlf-info".
=> bug fix: wrong plaquette in metadata just after reversibility check

solver/eigenvalues.c
Fix this
```
/usr/bin/ld: ./lib/libsolver.a(eigenvalues.o):/home/francesco/QCD/SORGENTI/tmLQCD/build_quda/solver/../../solver/eigenvalues.c:61: multiple definition of `no_eigenvalues'; ./lib/libhmc.a(read_input.o):/home/francesco/QCD/SORGENTI/tmLQCD/build_quda/../read_input.l:222: first defined here
```
=> no_eigenvalues already defined extern in the related header

block.c
Solving this additional error, similar to #485 
```
/usr/bin/ld: ./lib/libxchange.a(little_field_gather.o):/home/francesco/QCD/SORGENTI/tmLQCD/build_quda/xchange/../../xchange/little_field_gather.c:47: multiple definition of `Direction'; ./lib/libhmc.a(block.o):/home/francesco/QCD/SORGENTI/tmLQCD/build_quda/../block.c:78: first defined here
```
=> Additional Direction not needed

invert_doublet_eo.c, monomial/monomial.c, operator.c, quda_interface.c, quda_interface.h, read_input.l, solver/solver_params.h
Add back support for writing something like
```
BeginMonomial NDCLOVERRAT
Timescale = 1
kappa = 0.1400645
CSW = 1.74
AcceptancePrecision =  1e-21
ForcePrecision = 1e-16
StildeMin = 0.0000376
StildeMax = 4.7
MaxSolverIterations = 500
Name = ndcloverrat_0_3
DegreeOfRational = 10
Cmin = 0
Cmax = 3
ComputeEVFreq = 0
2Kappamubar = 0.0394421632
2Kappaepsbar = 0.0426076209
AddTrLog = yes
UseExternalInverter = quda
UseSloppyPrecision = single
RefinementPrecision = half    # <- refinement precision                                                                                                                                                                                                                                                
solver = cgmmsnd
EndMonomial
```
which allows the multi-shift …
=> re-expose refinenement precision

misc_types.h
I'm in the process o fixing a nasty segmentation fault that arises in random places around. With the help of @Marcogarofalo 
I've managed to run the code under valgrind, and I'm proceeding to fix each complain in turn, this is the first one
```
==20258== Use of uninitialised value of size 8
==20258==    at 0xBD369EC: __printf_fp_l (in /usr/lib64/power9/libc-2.28.so)
==20258==    by 0x1FFF007AAF: ???
==20258==    by 0xBD32623: printf_positional (in /usr/lib64/power9/libc-2.28.so)
==20258==    by 0xBD33BDF: vfprintf@@GLIBC_2.17 (in /usr/lib64/power9/libc-2.28.so)
==20258==    by 0x10045397: vprintf (stdio.h:41)
==20258==    by 0x10045397: tm_debug_printf (tm_debug_printf.c:35)
==20258==    by 0x100481F7: _loadGaugeQuda (quda_interface.c:565)
==20258==    by 0x1004BDB3: …
```
=> Ensure gauge_id member is initialized when the gauge_status is created

quda_interface.c, read_input.l
mg_eig_preserve_deflation is now supported even in QUDA-1.1.x, no need to guard it with TM_QUDA_EXPERIMENTAL
=> mg_eig_preserve_deflation does not need to guarded any more

quda_interface.c
always set inv_param.dagger to make sure that we don't accidentally re-use the parameter from the previous solve
=> fix online meaurements with QUDA when running the HMC

gettime.c, monomial/detratio_monomial.c, quda_interface.c, quda_types.h
This fixes one more bug due to which yet another instance of a dangling pointer in the MG Setup is resolved. This re-appared due to fixing another part of the logic through 221bf0980da0128df8d9f2702f65f7ab1cc19c69).
As a nice side effect, it reduces the number of Setup updates that should occur during the HMC (the setup will only be updated when necessary).
=> change mechanism by which QUDA MG state's dependence on state of gauge (and clover) field is tracked

profiling/hmc_mk2/profile.Rmd
I found confusing in the profile tool the position of the tables
so I did two things:
- Force the table to be placed in the same subsection;
- Add a caption to the table.
the result is now the following
=> tables position within same section + caption

quda_interface.c, quda_types.h
Reply to the issue https://github.com/etmc/tmLQCD/issues/527 .
I edited the ```quda_interface.c``` file as follows:
- I created a function ```void forceRegenerateMGSetupQuda(const CompressionType compression)``` which regenerates the MG setup.
* At the beginning ```_loadGaugeQuda()``` is called. For how it is implemented now, maybe it's redundant because this function is always called after one call of that function.
* In order to destroy the MG setup, the same MG-related functions called in ```_endQuda()``` are used.
* In order to regenerate the MG setup, the same MG-related functions called in ```_initQuda()``` are used.
- This function is called inside each ```invert_*()``` function defined in that file, whenever one's using the MG and the latter didn't converge.
- Any time the MG …
=> Quda regenerate mg setup

configure.in
This seems to work for me to link QUDA with CUDA. I haven't tried QUDA with HIP yet.
=> move checking for CUDA or HIP libraries outside of the QUDA config block

configure.in
in progress: changes to configure.in so that we can support both cuda and hip backends for quda.
=> specify quda backend

quda_interface.c
When I was adding the HMC additions, I accidentally messed up the logic for `coarse_grid_solution_type` and was injecting a full field on all intermediate and coarse levels :facepalm:
This PR significantly improves MG performance (4 Booster nodes, 64c128 lattice, physical point) and will also restore analysis performance to previous levels:
```
GCR: Convergence at 53 iterations, L2 relative residual: iterated = 7.315033e-10, true = 7.315033e-10 (requested = 1.000000e-09)
```
```
```
Just need to make sure that it doesn't break anything, but this will help us quite a bit...
=> change logic for setting MG param coarse_grid_solution_type

doc/input.tex
In the documentation to parameter was called `BarrierMonomialsConvergence`, not `BarrierMonomialsConverge`, resulting in a failure when parsing the input file.
=> typo in documentation: BarrierMonomialsConverge

Makefile.in, compare_derivative.c, compare_derivative.h, monomial/cloverdet_monomial.c, monomial/cloverdetratio_monomial.c, monomial/gauge_monomial.c
I've also removed the "relative" deviation business completely. I think what's relevant is the absolute deviation. We should perform a rather strict check, probably stricter than done here so far (by setting stricter thresholds in the monomials).
=> move compare_derivative into its own compilation unit and make the strictness variable, specify a 'name' argument

profiling/hmc_mk2/README.md, profiling/hmc_mk2/make_profile.R, profiling/hmc_mk2/profile.Rmd
Through a third command line argument, in the per-monomial tables and plots rather than grouping timings below 5% in the 'other' category, all timings can now be shown.
=> in the hmc_mk2 profiler, optionally include all timings

quda_interface.c
matching https://github.com/lattice/quda/commit/5d5450216c882d964fc8d88a279e77f7f930ba71
=> Remove legacy QudaInvertParam::tune parameter and remove unneeded enum QudaTune, quda 5d54502
